// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client. It prefers service-role credentials and falls
// back to the publishable credentials for explicitly granted public RPCs.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function configuredSupabasePublicCredentials(): { url: string; key: string } {
  const url = process.env["SUPABASE_URL"]?.trim() || import.meta.env["VITE_SUPABASE_URL"]?.trim();
  const key =
    process.env["SUPABASE_PUBLISHABLE_KEY"]?.trim() ||
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"]?.trim();
  if (!url || !key) {
    const missing = [
      !url ? "VITE_SUPABASE_URL (or SUPABASE_URL)" : "",
      !key ? "VITE_SUPABASE_PUBLISHABLE_KEY (or SUPABASE_PUBLISHABLE_KEY)" : "",
    ]
      .filter(Boolean)
      .join(", ");
    throw new Error(`Missing Supabase environment variable(s): ${missing}`);
  }
  return { url, key };
}

function createSupabaseAdminClient() {
  const serverUrl = process.env["SUPABASE_URL"]?.trim();
  const serviceRoleKey = process.env["SUPABASE_SERVICE_ROLE_KEY"]?.trim();
  const serverPublishableKey = process.env["SUPABASE_PUBLISHABLE_KEY"]?.trim();
  const viteUrl = import.meta.env["VITE_SUPABASE_URL"]?.trim();
  const vitePublishableKey = import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"]?.trim();
  const undefinedVariables = [
    ...(!serverUrl ? ["SUPABASE_URL"] : []),
    ...(!serviceRoleKey ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ...(!serverPublishableKey ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ...(!viteUrl ? ["VITE_SUPABASE_URL"] : []),
    ...(!vitePublishableKey ? ["VITE_SUPABASE_PUBLISHABLE_KEY"] : []),
  ];

  if (undefinedVariables.length > 0) {
    console.warn(`[Supabase] Undefined environment variables: ${undefinedVariables.join(", ")}`);
  }

  const SUPABASE_URL = serverUrl || viteUrl;
  const SUPABASE_KEY = serviceRoleKey || serverPublishableKey || vitePublishableKey;

  if (!SUPABASE_URL || !SUPABASE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL or VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY or VITE_SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client. Never expose this module to client code.
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});

// Public-key client used only for Supabase Auth flows that must establish the
// caller's verified session. Never use it for privileged database writes.
export function createSupabaseAuthClient() {
  const { url, key } = configuredSupabasePublicCredentials();
  return createClient<Database>(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}
